### ISSUE TITLE
ESPN Changed URL

### ISSUE THREAD

**Issue by rpmullig** [wcrasta/ESPN-Fantasy-Basketball#6]
ESPN Fantasy Basketball has changed its URL and layout of the league. I cannot figure out how to paste the new format in, and the example URL doesn't work anymore either.

**Comment by wcrasta** [comment]
Hey Bobby,

Thanks for your message. With the new ESPN layout for fantasy basketball, this app no longer works. It's unfortunate that ESPN decided to change their layout, as they've taken away quite a bit of functionality. In the coming days (likely over the weekend), I'll assess how much work is needed to get things working again and make a judgement call to see if it's worth the effort.

**Comment by rpmullig** [comment]
I'm here to help as much I can. I am new to open source, but I wouldn't mind helping my fantasy team out

**Comment by wcrasta** [comment]
The core logic once everything has been scraped should all be the same, it's just that ESPN has re-designed the page so some scraping logic must change .

I'm having a tough time scraping the scoreboard, and have [posted a question on StackOverflow here](https://stackoverflow.com/questions/52910520/how-to-scrape-page-with-beautifulsoup-page-source-not-matching-inspect-element) for help. If you can figure out how to scrape the scoreboard page, it would be a huge help. Feel free to give it a shot.

**Comment by wcrasta** [comment]
Ignore the above comment. I'm making good progress.

**Comment by wcrasta** [comment]
Fixed. See http://fantasy.warrencrasta.com
